behaviors:
  SparringAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 500000
      buffer_init_steps: 2500
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          hidden_units: 256

    keep_checkpoints: 5
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 16384
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      window: 30
      play_against_latest_model_ratio: 0.6
      initial_elo: 1200.0

env_settings:
  num_areas: 24

